// Re-export types from shared package for backward compatibility
export type {
  CategoryWithCount,
  ExpenseWithCategory,
  IncomeApi as IncomeType,
  Income,
  Expense,
  Category,
  CreateIncomeDto,
  UpdateIncomeDto,
  CreateExpenseDto,
  UpdateExpenseDto,
  CreateCategoryDto,
  UpdateCategoryDto,
  IncomeApiResponse,
  IncomesApiResponse,
  ExpenseApiResponse,
  ExpensesApiResponse,
  CategoryApiResponse,
  CategoriesApiResponse,
  CategoryWithCountApiResponse,
  ApiResponse,
  ApiErrorResponse,
  PaginatedResponse,
} from 'expenses-shared';
