name: Deploy Application

on:
  push:
    branches: [main]
    paths:
      - 'apps/backend/**'
      - 'apps/web/**'
      - 'packages/shared/**'
      - '.github/workflows/deploy.yml'
      - '.github/actions/**'

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '9.0.0'

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    outputs:
      api-gateway-url: ${{ steps.backend-deploy.outputs.api-gateway-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: '8' # Backend uses pnpm version 8
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Backend
        id: backend-deploy
        uses: ./.github/actions/deploy-backend
        with:
          pulumi-config-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          db-secret: ${{ secrets.DB_SECRET }}
          jwt-secret: ${{ secrets.JWT_SECRET }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Frontend
        uses: ./.github/actions/deploy-frontend
        with:
          api-gateway-url: ${{ needs.deploy-backend.outputs.api-gateway-url }}
          pulumi-config-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
